### PR TITLE
Frontpage - Fix images and allow github pages

### PR DESCRIPTION
**Pull request by alx741**
With the new directory tree of `lessons` the images links broke, this PR fix it.

The front page is now in the `docs` directory so the repo can be [configured like this](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) and be accessible at http://snoyberg.github.io/magical-guide-haskell

### CODE REVIEW

**Comment by snoyberg** [comment]
Cool, let's try it!

**Comment by snoyberg** [comment]
It sort of works, but looks like there's no index.html. This page _does_ work, for instance:

https://snoyberg.github.io/magical-guide-haskell/lessons/en/programs.html

**Comment by alx741** [comment]
Oops!, didn't make sure it was on the generated site, my bad.

Fixed on #4

**Comment by alx741** [comment]
Thanks for the invitation BTW. The styling for showing the lessons is missing and the responsiveness needs some work, I'll keep working on those.

For now, it's looking good: https://snoyberg.github.io/magical-guide-haskell/

**Pull request merged**
