### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by alx741**
This project is a really great idea, and look really promising!
I have a 9yo nephew that is asking me to teach him programming, I'm definitely going to try with this content.

The thing is our native language is spanish, so I though contributing to this with the translation; Hopefully other people will contribute with other languages as well.

This PR translates only the first section of the `programs` document, so you can let me know if you'd like to have the translation in here; If you prefer to keep this repo with the english version only, please feel free to dismiss this.

### CODE REVIEW

**Comment by snoyberg** [comment]
This is awesome, it made me really happy to see! I'm AFK for the next two
days, I'll write back on Sunday in more detail. My only concern is that,
right now, the English content will be changing a _lot_ and I don't want to
cause you to waste a lot of time. But I'm totally in favor of this, and
really excited.

On Fri, Jun 23, 2017 at 4:46 AM, Daniel Campoverde <notifications@github.com

**Comment by alx741** [comment]
> the English content will be changing a _lot_ 

Maybe I could wait until each document reaches some degree of stability before translating it. They would still be prone to change but it would be smaller changes that I could keep up with I guess.

If you could ping me back when you consider each document is, to some extent, ready for translation I would happily do it.

**Comment by snoyberg** [comment]
That sounds like a great plan. FYI, I'm planning on splitting up the first lesson into smaller lessons (my wife's feedback, we think my son will get bored with one long lesson). The only other question is whether you want to get pinged after I've finished writing it, or after my son has tried the lesson and I get feedback from real life usage. I'm happy to ping either way (or both).

**Comment by alx741** [comment]
If you let me know after both that would be great, so I can start writing the translation ASAP and try it out with my nephew as well to get some additional feedback for both the content and translation; Some information tends to get lost in translation + there is almost no haskell content in spanish, so I couldn't just show him official documentation... I'm eager to see how to make that work out.

**EDIT:** I mean my nephew

**Comment by snoyberg** [comment]
Awesome! Well in that case, the first lesson is done and my son went
through it, with no feedback yet. The second lesson is still under review
by my wife, but no major changes planned.

On Sun, Jun 25, 2017 at 6:56 PM, Daniel Campoverde <notifications@github.com

**Comment by alx741** [comment]
Perfect, will write the translation tonight and try it out (hopefully) during this week

**Comment by snoyberg** [comment]
Nice!

On Sun, Jun 25, 2017 at 7:13 PM, Daniel Campoverde <notifications@github.com

**Comment by alx741** [comment]
Alright! The translation for the first two lessons is ready. I'll hand this to my nephew this Saturday and tweak it a bit with the feed back

**Comment by alx741** [comment]
My nephew went thought it and gave me some feed back about clarifications that were needed in the translation, so no information gets lost.

The Spanish translation for the first two lessons is ready now, I'll figure out how to integrate the translations  in the front page nicely, as the title and description (in the front page) need translations as well.

**Pull request merged**
